CREATE TABLE [STG_BLOG] (
  [BLOG_ID] TEXT NOT NULL, 
  [USER_ID] TEXT NOT NULL, 
  [TOUR_ID] TEXT NOT NULL, 
  [SUB_TOUR_ID] TEXT NOT NULL, 
  [SIGHTS_ID] TEXT NOT NULL, 
  [TITLE] TEXT, 
  [CONTENT] TEXT, 
  [CREATING_TIME] DATETIME, 
  CONSTRAINT [STG_BLOG_PK] PRIMARY KEY ([BLOG_ID]));

CREATE TABLE [STG_CITY] (
  [CITY_ID] TEXT NOT NULL, 
  [CITY_NAME] TEXT NOT NULL UNIQUE, 
  [PROVINCE_ID] TEXT NOT NULL, 
  CONSTRAINT [STG_CITY_PK] PRIMARY KEY ([CITY_ID]));

CREATE TABLE [STG_COUNTRY] (
  [COUNTRY_ID] TEXT NOT NULL, 
  [COUNTRY_NAME] TEXT NOT NULL UNIQUE, 
  CONSTRAINT [STG_COUNTRY_PK] PRIMARY KEY ([COUNTRY_ID]));

CREATE TABLE [STG_FAVORITE] (
  [USER_ID] TEXT NOT NULL, 
  [SIGHTS_ID] TEXT NOT NULL, 
  [VISITED] INTEGER NOT NULL, 
  [STARS] INTEGER NOT NULL, 
  [CREATING_TIME] DATETIME, 
  CONSTRAINT [STG_FAVORITE_PK] PRIMARY KEY ([USER_ID], [SIGHTS_ID]));

CREATE TABLE [STG_PERMISSION] (
  [USER_ID] TEXT NOT NULL, 
  [PERMISSION_TYPE] INTEGER NOT NULL, 
  CONSTRAINT [STG_PERMISSION_PK] PRIMARY KEY ([USER_ID], [PERMISSION_TYPE]));

CREATE TABLE [STG_PICTURE] (
  [PICTURE_ID] TEXT NOT NULL, 
  [SIGHTS_ID] TEXT NOT NULL, 
  [TOUR_ID] TEXT, 
  [SUB_TOUR_ID] TEXT, 
  [PATH] TEXT NOT NULL, 
  [DESCRIPTION] TEXT, 
  [USER_ID] TEXT NOT NULL, 
  [CREATING_TIME] DATETIME, 
  CONSTRAINT [STG_PICTURE_PK] PRIMARY KEY ([PICTURE_ID]));

CREATE TABLE [STG_PICTURE_COMMENT] (
  [COMMENT_ID] TEXT NOT NULL, 
  [PICTURE_ID] TEXT NOT NULL, 
  [COMM_USER_ID] TEXT NOT NULL, 
  [CREATING_TIME] DATETIME, 
  [COMMENT] TEXT, 
  CONSTRAINT [STG_PICTURE_COMMENT_PK] PRIMARY KEY ([COMMENT_ID]));

CREATE TABLE [STG_PROVINCE] (
  [PROVINCE_ID] TEXT NOT NULL, 
  [PROVINCE_NAME] TEXT NOT NULL UNIQUE, 
  [COUNTRY_ID] TEXT NOT NULL, 
  CONSTRAINT [STG_PROVINCE_PK] PRIMARY KEY ([PROVINCE_ID]));

CREATE TABLE [STG_SIGHTS] (
  [SIGHTS_ID] TEXT NOT NULL, 
  [SIGHTS_NAME] TEXT NOT NULL, 
  [CITY_ID] TEXT NOT NULL, 
  [SIGHTS_LEVEL] TEXT NOT NULL, 
  [DESCRIPTION] TEXT, 
  [PRICE] TEXT, 
  [CREATING_TIME] DATETIME, 
  [MEMOS] TEXT, 
  CONSTRAINT [STG_SIGHTS_PK] PRIMARY KEY ([SIGHTS_ID]));

CREATE TABLE [STG_SIGHTS_COMMENT] (
  [COMMENT_ID] TEXT NOT NULL, 
  [SIGHTS_ID] TEXT NOT NULL, 
  [COMM_USER_ID] TEXT NOT NULL, 
  [CREATING_TIME] DATETIME, 
  [COMMENT] TEXT, 
  CONSTRAINT [STG_SIGHTS_COMMENT_PK] PRIMARY KEY ([COMMENT_ID]));

CREATE TABLE [STG_SUB_TOUR] (
  [TOUR_ID] TEXT NOT NULL, 
  [SUB_TOUR_ID] TEXT NOT NULL, 
  [SUB_TOUR_NAME] TEXT NOT NULL, 
  [SIGHTS_ID] TEXT NOT NULL, 
  [BEGIN_DATE] DATETIME, 
  [END_DATE] DATETIME, 
  [CREATING_TIME] DATETIME, 
  [MEMOS] TEXT, 
  CONSTRAINT [STG_SUB_TOUR_PK] PRIMARY KEY ([TOUR_ID], [SUB_TOUR_ID]));

CREATE TABLE [STG_TOUR] (
  [TOUR_ID] TEXT NOT NULL, 
  [TOUR_NAME] TEXT NOT NULL, 
  [USER_ID] TEXT NOT NULL, 
  [BEGIN_DATE] DATETIME, 
  [END_DATE] DATETIME, 
  [COST] INTEGER, 
  [STATUS] INTEGER, 
  [CREATING_TIME] DATETIME, 
  [MEMOS] TEXT, 
  CONSTRAINT [STG_TOUR_PK] PRIMARY KEY ([TOUR_ID]));

CREATE TABLE [STG_TOUR_COMMENT] (
  [COMMENT_ID] TEXT NOT NULL, 
  [TOUR_ID] TEXT NOT NULL, 
  [COMM_USER_ID] TEXT NOT NULL, 
  [CREATING_TIME] DATETIME, 
  [COMMENT] TEXT, 
  CONSTRAINT [STG_TOUR_COMMENT_PK] PRIMARY KEY ([COMMENT_ID]));

CREATE TABLE [STG_USER] (
  [USER_ID] TEXT NOT NULL, 
  [LOGIN_NAME] TEXT NOT NULL UNIQUE, 
  [PASSWORD] TEXT NOT NULL, 
  [EMAIL] TEXT, 
  [STATUS] INTEGER NOT NULL, 
  CONSTRAINT [STG_USER_PK] PRIMARY KEY ([USER_ID]));

CREATE TABLE [STG_USER_COMMENT] (
  [COMMENT_ID] TEXT NOT NULL, 
  [USER_ID] TEXT NOT NULL, 
  [COMM_USER_ID] TEXT NOT NULL, 
  [CREATING_TIME] DATETIME, 
  [COMMENT] TEXT, 
  CONSTRAINT [STG_USER_COMMENT_PK] PRIMARY KEY ([COMMENT_ID]));

